import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

type Language = 'en' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    createBeautiful: 'Start your tier list by choosing your favorite universe',
    selectPokemonLanguage: 'Choose the language for Pokémon names',
    chooseLanguage: 'Choose a language',
    english: 'English',
    french: 'French',
    spanish: 'Spanish',
    selectTemtemVariant: 'Select a Temtem variant',
    chooseVariant: 'Choose a variant',
    normal: 'Normal',
    luma: 'Luma',
    backToHome: 'Back to Home',
    customizeYour: 'Customize your',
    tierList: 'Tier List',
    selectWhich: 'Select the',
    youWant: 'you want to include in your tier list:',
    pleaseSelectLanguage: 'Please select a language first',
    pleaseSelectVariant: 'Please select a variant first',
    pleaseSelectOption: 'Please select at least one option to continue',
    continue: 'Continue',
    addCustomCharacter: 'Add a custom character',
    characterName: 'Character name',
    enterCharacterName: 'Enter the character\'s name',
    addToTierList: 'Add to tier list',
    cancel: 'Cancel',
    dragDrop: 'Drag & drop an image or',
    browse: 'browse',
    fileSize: 'PNG, JPG or GIF up to 5MB',
    exportShare: 'Export & Share',
    saveAsImage: 'Save as image',
    exportJson: 'Export JSON',
    copyShareLink: 'Copy share link',
    linkCopied: 'Link copied!',
    backToFilters: 'Back to filters',
    dragCharactersHere: 'Drag characters here',
    save: 'Save',
    editTier: 'Edit tier',
    deleteTier: 'Delete tier',
    addTier: 'Add tier',
    charactersPool: 'Unranked characters',
    unknownCharacters: 'Unknown characters',
    noUnknownCharacters: 'No unknown characters',
    orderWebsite: 'Your custom website here',
    createCustomTierList: 'Create a custom tier list',
    customTierList: 'Custom tier list',
    giveFeedback: 'Give us your feedback',
    pokemonName: 'Pokémon',
    pokemonDescription: 'Rank your favorite Pokémon by generation',
    narutoName: 'Naruto',
    narutoDescription: 'Rank the ninjas from the Naruto universe',
    demonSlayerName: 'Demon Slayer',
    demonSlayerDescription: 'Rank Demon Slayer characters by season',
    leagueOfLegendsName: 'League of Legends',
    leagueOfLegendsDescription: 'Rank your favorite champions by role',
    onepieceName: 'One Piece',
    onepieceDescription: 'Rank the characters from One Piece',
    temtemName: 'Temtem',
    temtemDescription: 'Rank Temtem creatures by type and variant (normal or luma)',
    generation1: 'Generation 1',
    generation2: 'Generation 2',
    generation3: 'Generation 3',
    generation4: 'Generation 4',
    generation5: 'Generation 5',
    generation6: 'Generation 6',
    generation7: 'Generation 7',
    generation8: 'Generation 8',
    generation9: 'Generation 9',
    season1: 'Season 1',
    season2: 'Season 2 (Entertainment District Arc)',
    season3: 'Season 3 (Swordsmith Village Arc)',
    season4: 'Season 4 (Hashira Training Arc)',
    assassin: 'Assassin',
    fighter: 'Fighter',
    mage: 'Mage',
    marksman: 'Marksman',
    support: 'Support',
    tank: 'Tank',
    typeNeutral: 'Neutral',
    typeWind: 'Wind',
    typeEarth: 'Earth',
    typeWater: 'Water',
    typeFire: 'Fire',
    typeNature: 'Nature',
    typeElectric: 'Electric',
    typeDigital: 'Digital',
    typeMental: 'Mental',
    typeMelee: 'Melee',
    typeCrystal: 'Crystal',
    typeToxic: 'Toxic',
    activateNightMode: 'Enable dark mode',
    activateDayMode: 'Enable light mode',
    editTierDetails: 'Edit tier title and color'
  },
  fr: {
    createBeautiful: 'Commence ta tier list en choisissant ton univers préféré',
    selectPokemonLanguage: 'Choisis la langue des noms de Pokémon',
    chooseLanguage: 'Choisis une langue',
    english: 'Anglais',
    french: 'Français',
    spanish: 'Espagnol',
    selectTemtemVariant: 'Choisis la variante de Temtem',
    chooseVariant: 'Choisis une variante',
    normal: 'Normal',
    luma: 'Luma',
    backToHome: 'Retour à l\'accueil',
    customizeYour: 'Personnalise ta',
    tierList: 'Tier List',
    selectWhich: 'Sélectionne les',
    youWant: 'que tu veux inclure dans ta tier list :',
    pleaseSelectLanguage: 'Merci de choisir une langue en premier',
    pleaseSelectVariant: 'Merci de choisir une variante en premier',
    pleaseSelectOption: 'Merci de sélectionner au moins une option pour continuer',
    continue: 'Continuer',
    addCustomCharacter: 'Ajouter un personnage personnalisé',
    characterName: 'Nom du personnage',
    enterCharacterName: 'Entre le nom du personnage',
    addToTierList: 'Ajouter à la tier list',
    cancel: 'Annuler',
    dragDrop: 'Glisse-dépose une image ou',
    browse: 'parcourir',
    fileSize: 'PNG, JPG ou GIF jusqu\'à 5 Mo',
    exportShare: 'Exporter & Partager',
    saveAsImage: 'Enregistrer en image',
    exportJson: 'Exporter JSON',
    copyShareLink: 'Copier le lien de partage',
    linkCopied: 'Lien copié !',
    backToFilters: 'Retour aux filtres',
    dragCharactersHere: 'Glisse les personnages ici',
    save: 'Enregistrer',
    editTier: 'Modifier le tier',
    deleteTier: 'Supprimer le tier',
    addTier: 'Ajouter un tier',
    charactersPool: 'Personnages non classés',
    unknownCharacters: 'Personnages inconnus',
    noUnknownCharacters: 'Aucun personnage inconnu',
    orderWebsite: 'Ton site web sur-mesure ici',
    giveFeedback: 'Donne nous tes feedbacks',
    createCustomTierList: 'Créer une tier list personnalisée',
    customTierList: 'Tier list personnalisée',
    pokemonName: 'Pokémon',
    pokemonDescription: 'Classe tes Pokémon préférés par génération',
    narutoName: 'Naruto',
    narutoDescription: 'Classe les ninjas de l’univers Naruto',
    demonSlayerName: 'Demon Slayer',
    demonSlayerDescription: 'Classe les personnages de Demon Slayer par saison',
    leagueOfLegendsName: 'League of Legends',
    leagueOfLegendsDescription: 'Classe tes champions préférés par rôle',
    onepieceName: 'One Piece',
    onepieceDescription: 'Classe les personnages de One Piece',
    temtemName: 'Temtem',
    temtemDescription: 'Classe les créatures Temtem par type (normal ou luma)',
    generation1: 'Génération 1',
    generation2: 'Génération 2',
    generation3: 'Génération 3',
    generation4: 'Génération 4',
    generation5: 'Génération 5',
    generation6: 'Génération 6',
    generation7: 'Génération 7',
    generation8: 'Génération 8',
    generation9: 'Génération 9',
    season1: 'Saison 1',
    season2: 'Saison 2 (Arc du quartier des plaisirs)',
    season3: 'Saison 3 (Arc du village des forgerons)',
    season4: 'Saison 4 (Entraînement des piliers)',
    assassin: 'Assassin',
    fighter: 'Combattant',
    mage: 'Mage',
    marksman: 'Tireur',
    support: 'Support',
    tank: 'Tank',
    typeNeutral: 'Neutre',
    typeWind: 'Vent',
    typeEarth: 'Terre',
    typeWater: 'Eau',
    typeFire: 'Feu',
    typeNature: 'Nature',
    typeElectric: 'Électrique',
    typeDigital: 'Digital',
    typeMental: 'Mental',
    typeMelee: 'Mêlée',
    typeCrystal: 'Cristal',
    typeToxic: 'Toxique',
    activateNightMode: 'Activer le mode nuit',
    activateDayMode: 'Activer le mode jour',
    editTierDetails: 'Modifier le titre et la couleur du tier'
  },
  es: {
    createBeautiful: 'Comienza tu tier list eligiendo tu universo favorito',
    selectPokemonLanguage: 'Elige el idioma de los nombres de Pokémon',
    chooseLanguage: 'Elige un idioma',
    english: 'Inglés',
    french: 'Francés',
    spanish: 'Español',
    selectTemtemVariant: 'Elige la variante de Temtem',
    chooseVariant: 'Elige una variante',
    normal: 'Normal',
    luma: 'Luma',
    backToHome: 'Volver al inicio',
    customizeYour: 'Personaliza tu',
    tierList: 'Tier List',
    selectWhich: 'Selecciona los',
    youWant: 'que quieres incluir en tu tier list:',
    pleaseSelectLanguage: 'Por favor, elige primero un idioma',
    pleaseSelectVariant: 'Por favor, elige primero una variante',
    pleaseSelectOption: 'Selecciona al menos una opción para continuar',
    continue: 'Continuar',
    addCustomCharacter: 'Agregar personaje personalizado',
    characterName: 'Nombre del personaje',
    enterCharacterName: 'Escribe el nombre del personaje',
    addToTierList: 'Agregar a la tier list',
    cancel: 'Cancelar',
    dragDrop: 'Arrastra y suelta una imagen o',
    browse: 'explora',
    fileSize: 'PNG, JPG o GIF de hasta 5 MB',
    exportShare: 'Exportar y compartir',
    saveAsImage: 'Guardar como imagen',
    exportJson: 'Exportar JSON',
    copyShareLink: 'Copiar enlace de compartir',
    linkCopied: '¡Enlace copiado!',
    backToFilters: 'Volver a los filtros',
    dragCharactersHere: 'Arrastra los personajes aquí',
    save: 'Guardar',
    editTier: 'Editar tier',
    deleteTier: 'Eliminar tier',
    addTier: 'Agregar tier',
    charactersPool: 'Personajes sin clasificar',
    unknownCharacters: 'Personajes desconocidos',
    noUnknownCharacters: 'No hay personajes desconocidos',
    orderWebsite: 'Tu sitio web a medida aquí',
    createCustomTierList: 'Crear una tier list personalizada',
    customTierList: 'Tier list personalizada',
    giveFeedback: 'Danos tus comentarios',
    pokemonName: 'Pokémon',
    pokemonDescription: 'Clasifica tus Pokémon favoritos por generación',
    narutoName: 'Naruto',
    narutoDescription: 'Clasifica a los ninjas del universo Naruto',
    demonSlayerName: 'Demon Slayer',
    demonSlayerDescription: 'Clasifica los personajes de Demon Slayer por temporada',
    leagueOfLegendsName: 'League of Legends',
    leagueOfLegendsDescription: 'Clasifica tus campeones favoritos por rol',
    onepieceName: 'One Piece',
    onepieceDescription: 'Clasifica los personajes de One Piece',
    temtemName: 'Temtem',
    temtemDescription: 'Clasifica las criaturas Temtem por tipo y variante (normal o luma)',
    generation1: 'Generación 1',
    generation2: 'Generación 2',
    generation3: 'Generación 3',
    generation4: 'Generación 4',
    generation5: 'Generación 5',
    generation6: 'Generación 6',
    generation7: 'Generación 7',
    generation8: 'Generación 8',
    generation9: 'Generación 9',
    season1: 'Temporada 1',
    season2: 'Temporada 2 (Arco del distrito del entretenimiento)',
    season3: 'Temporada 3 (Arco de la aldea de los herreros)',
    season4: 'Temporada 4 (Entrenamiento de los pilares)',
    assassin: 'Asesino',
    fighter: 'Luchador',
    mage: 'Mago',
    marksman: 'Tirador',
    support: 'Soporte',
    tank: 'Tanque',
    typeNeutral: 'Neutral',
    typeWind: 'Viento',
    typeEarth: 'Tierra',
    typeWater: 'Agua',
    typeFire: 'Fuego',
    typeNature: 'Naturaleza',
    typeElectric: 'Eléctrico',
    typeDigital: 'Digital',
    typeMental: 'Mental',
    typeMelee: 'Cuerpo a cuerpo',
    typeCrystal: 'Cristal',
    typeToxic: 'Tóxico',
    activateNightMode: 'Activar modo nocturno',
    activateDayMode: 'Activar modo diurno',
    editTierDetails: 'Editar el título y el color del tier'   
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'fr',
  setLanguage: () => {},
  t: key => translations['fr'][key] || key
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== 'undefined' && localStorage.getItem('language')) {
      return localStorage.getItem('language') as Language;
    }
    return 'fr';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = useCallback((key: string) => translations[language][key] || translations['fr'][key] || key, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

